CSA-54: Implement endpoint to generate a JWT token
bootcamp2024-quantum/core-backend pull request #11
Opened 2024-03-21 15:40 UTC by AlfurIvan

Created functional for obtaining JWT access and refresh tokens. Tested.

2024-03-22 20:51 UTC, ssliadniev requested changes

2024-03-22 20:51 UTC, ssliadniev commented on career_skill_atlas/config/base_settings.py
> +SECRET_KEY = "fooadfasdfasdf"
never store secret envs in the code

2024-03-22 20:51 UTC, ssliadniev commented on career_skill_atlas/urls.py
> +    path("", include("user.urls")),
can drop cause users urls already in `api/`

2024-03-22 21:55 UTC, AlfurIvan commented on career_skill_atlas/config/base_settings.py
> +SECRET_KEY = "fooadfasdfasdf"
For sure, got it

2024-03-23 11:04 UTC, ssliadniev approved these changes

2024-03-23 11:04 UTC, merged