CSA-64 Implement /roadmaps/search endpoint
bootcamp2024-quantum/core-backend pull request #23
Opened 2024-03-28 18:17 UTC by AlfurIvan

2024-04-04 15:59 UTC, bogdan-bridgewise requested changes

2024-04-04 15:59 UTC, bogdan-bridgewise commented on roadmap/views.py
> +                "code": status.HTTP_406_NOT_ACCEPTABLE
why do we return 406 and not 400 ? look what errors could be return in open api schema

2024-04-04 18:47 UTC, bogdan-bridgewise approved these changes

2024-04-04 20:56 UTC, bogdan-bridgewise submitted a review, later dismissed

2024-04-04 20:56 UTC, bogdan-bridgewise commented on roadmap/views.py
> +    permission_classes = [IsNotDefaultUser]
we should allow anyone to get domains list

2024-04-04 20:56 UTC, bogdan-bridgewise commented on roadmap/views.py
> +    permission_classes = [IsNotDefaultUser]
same here

2024-04-08 08:05 UTC, ssliadniev approved these changes

2024-04-08 08:05 UTC, ssliadniev commented on roadmap/admin.py
> +from roadmap import models
let's import specific models from `roadmap.models`

2024-04-08 08:05 UTC, ssliadniev commented on roadmap/admin.py
> +admin.site.register(models.Tag, SmallModelAdmin)
Not best approach to create one admin model for several models. 
It reduce code duplication, but it lead to less flexibility and maintainability in the future.
So, let's create a separate admin model for each roadmap related models.

2024-04-08 08:16 UTC, merged